version: "3"
services:
  web1:
    build:
      dockerfile: ./docker/python/dockerfile
      context: ./
    image: flask_app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    env_file: '.env'
    networks:
      - app1

  database:
    image: mysql:8.0
    container_name: "databaseflask"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "yura01"
      MYSQL_DATABASE: "yura01"
      MYSQL_USER: "yura01"
      MYSQL_PASSWORD: "yura01"
    ports:
      - 3310:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - app1

  nginx:
    image: nginx:1.23-alpine
    container_name: nginx
    ports:
      - 1440:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/code
    networks:
      - app1
    depends_on:
      - web1



networks:
  app1:
    driver: bridge