"""Data in ads

Revision ID: 30e648be1593
Revises: 9cd053b5ca5d
Create Date: 2023-08-16 18:26:52.302450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e648be1593'
down_revision = '9cd053b5ca5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('registration_date')

    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('registration_date')

    # ### end Alembic commands ###
