"""on the new pc, with new description

Revision ID: 9cd053b5ca5d
Revises: dea86e523a43
Create Date: 2023-08-16 09:55:29.570927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd053b5ca5d'
down_revision = 'dea86e523a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('power', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('color', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('power')

    # ### end Alembic commands ###
