"""M with m

Revision ID: dea86e523a43
Revises: b8e227df24ab
Create Date: 2023-08-10 12:24:15.023947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea86e523a43'
down_revision = 'b8e227df24ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelcar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mark_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mark_id'], ['mark.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modelcar')
    # ### end Alembic commands ###
